export type FileType = "PDF" | "DOCX" | "PPTX" | "ZIP";

export type Note = {
  id: string;
  title: string;
  subject: string;
  semester: string;
  courseCode: string;
  unit: string;
  topic: string;
  uploader: string;
  uploaderRole: string;
  uploaderAvatar?: string;
  fileType: FileType;
  fileSize: string;
  uploadDate: string;
  rating: number;
  ratingsCount: number;
  downloads: number;
  tags: string[];
  summary: string;
  ownerId: "current-user" | "community";
  saved: boolean;
  coverImage?: string;
  pages?: number;
};

export type UploadDraft = {
  title: string;
  subject: string;
  semester: string;
  courseCode: string;
  unit: string;
  fileType: FileType;
  tags: string;
  summary: string;
  fileName: string;
};

export const currentUser = {
  id: "current-user",
  name: "Arjun Mehta",
  role: "Student",
  email: "arjun.mehta@classvault.edu",
  avatar: "/avatar_arjun.png",
};

export const emptyUploadDraft: UploadDraft = {
  title: "",
  subject: "",
  semester: "5",
  courseCode: "",
  unit: "",
  fileType: "PDF",
  tags: "",
  summary: "",
  fileName: "",
};

export const initialNotes: Note[] = [
  {
    id: "note-dbms-unit2",
    title: "DBMS – Unit 2 Notes",
    subject: "Database Systems",
    semester: "5",
    courseCode: "CS302",
    unit: "Unit 2",
    topic: "Relational Model & SQL",
    uploader: "Neha Sharma",
    uploaderRole: "CSE, 5th Semester",
    uploaderAvatar: "/avatar_neha.png",
    fileType: "PDF",
    fileSize: "1.8 MB",
    pages: 24,
    uploadDate: "12 May 2024",
    rating: 5.0,
    ratingsCount: 312,
    downloads: 2400,
    tags: ["DBMS", "Relational Model", "SQL", "Normalization", "Unit 2"],
    summary: "Comprehensive handwritten notes covering relational model, relational algebra, SQL queries, constraints and normalization techniques with solved examples.",
    ownerId: "community",
    saved: true,
    coverImage: "/card_dbms.png",
  },
  {
    id: "note-cn-complete",
    title: "Computer Networks",
    subject: "Computer Networks",
    semester: "7",
    courseCode: "CS401",
    unit: "Complete Notes (Unit 1–5)",
    topic: "TCP/IP, Routing, Protocol layers",
    uploader: "Arjun Mehta",
    uploaderRole: "CSE, 7th Semester",
    uploaderAvatar: "/avatar_arjun.png",
    fileType: "PDF",
    fileSize: "4.2 MB",
    pages: 58,
    uploadDate: "28 April 2024",
    rating: 4.8,
    ratingsCount: 142,
    downloads: 1800,
    tags: ["Networks", "TCP/IP", "Routing", "OSI Model"],
    summary: "Full semester notes covering the TCP/IP stack, physical layer encoding, sliding window protocols, routing algorithms (OSPF, BGP) and application layer protocol details.",
    ownerId: "current-user",
    saved: false,
    coverImage: "/card_networks.png",
  },
  {
    id: "note-ds-all",
    title: "Data Structures",
    subject: "Data Structures",
    semester: "3",
    courseCode: "CS201",
    unit: "All Units – Handwritten Notes",
    topic: "Trees, Graphs, Stacks & Queues",
    uploader: "Riya Patel",
    uploaderRole: "CSE, 3rd Semester",
    uploaderAvatar: "/avatar_riya.png",
    fileType: "PDF",
    fileSize: "3.5 MB",
    pages: 45,
    uploadDate: "05 May 2024",
    rating: 4.9,
    ratingsCount: 204,
    downloads: 2200,
    tags: ["Data Structures", "Trees", "Graphs", "Handwritten"],
    summary: "Clear handwritten diagrams and derivations for AVL trees, red-black trees, BFS/DFS traversal, Dijkstra's algorithm, and standard complexity cheat sheets.",
    ownerId: "community",
    saved: true,
    coverImage: "/card_dsa.png",
  },
  {
    id: "note-dld-short",
    title: "Digital Logic Design",
    subject: "Digital Logic Design",
    semester: "3",
    courseCode: "EC203",
    unit: "Short Notes + Examples",
    topic: "Gates, K-Maps, Sequentials",
    uploader: "Devansh Jain",
    uploaderRole: "ECE, 3rd Semester",
    uploaderAvatar: "/avatar_devansh.png",
    fileType: "PDF",
    fileSize: "2.1 MB",
    pages: 18,
    uploadDate: "18 April 2024",
    rating: 4.7,
    ratingsCount: 88,
    downloads: 1200,
    tags: ["K-Maps", "Logic Gates", "Flip-Flops", "Counters"],
    summary: "Compact last-minute revision notes with detailed truth tables, K-map minimization techniques, state reduction methods, and synchronous counter design steps.",
    ownerId: "community",
    saved: false,
    coverImage: "/card_digital.png",
  },
  {
    id: "note-os-notes",
    title: "Operating Systems Notes",
    subject: "Operating Systems",
    semester: "5",
    courseCode: "CS301",
    unit: "Unit 3 – Process Management",
    topic: "CPU Scheduling & Semaphores",
    uploader: "Neha Sharma",
    uploaderRole: "CSE, 5th Semester",
    uploaderAvatar: "/avatar_neha.png",
    fileType: "PDF",
    fileSize: "1.6 MB",
    pages: 12,
    uploadDate: "10 May 2024",
    rating: 4.8,
    ratingsCount: 95,
    downloads: 1600,
    tags: ["Scheduling", "Processes", "Semaphores"],
    summary: "Handwritten class notes on process states, context switching, CPU scheduling algorithms (SJF, Round Robin) with Gantt chart numericals, and classic synchronization problems.",
    ownerId: "community",
    saved: false,
  },
  {
    id: "note-dbms-norm",
    title: "DBMS – Normalization",
    subject: "Database Systems",
    semester: "5",
    courseCode: "CS302",
    unit: "Unit 2",
    topic: "Functional Dependencies & NF",
    uploader: "Arjun Mehta",
    uploaderRole: "CSE, 5th Semester",
    uploaderAvatar: "/avatar_arjun.png",
    fileType: "PDF",
    fileSize: "2.4 MB",
    pages: 20,
    uploadDate: "12 May 2024",
    rating: 5.0,
    ratingsCount: 312,
    downloads: 2400,
    tags: ["Normalization", "1NF", "2NF", "3NF", "BCNF"],
    summary: "Step-by-step normalization guide from 1NF to BCNF, closure sets, attribute dependency rules, and lossless join decomposition exercises with solutions.",
    ownerId: "current-user",
    saved: false,
  },
  {
    id: "note-ds-trees",
    title: "Data Structures – Trees",
    subject: "Data Structures",
    semester: "3",
    courseCode: "CS201",
    unit: "Unit 4",
    topic: "AVL, B-Trees & Traversal",
    uploader: "Riya Patel",
    uploaderRole: "CSE, 3rd Semester",
    uploaderAvatar: "/avatar_riya.png",
    fileType: "PDF",
    fileSize: "3.1 MB",
    pages: 15,
    uploadDate: "02 May 2024",
    rating: 4.9,
    ratingsCount: 172,
    downloads: 3100,
    tags: ["Trees", "AVL", "B-Tree", "Binary Trees"],
    summary: "Deep dive into binary tree properties, tree traversals, AVL rotations with numerical exercises, and basic operations on B-Trees and heap structures.",
    ownerId: "community",
    saved: false,
  },
  {
    id: "note-cn-pyqs",
    title: "Computer Networks – PYQs",
    subject: "Computer Networks",
    semester: "7",
    courseCode: "CS401",
    unit: "PYQs (2019–24)",
    topic: "Past exams and solutions",
    uploader: "Karan Verma",
    uploaderRole: "CSE, 7th Semester",
    uploaderAvatar: "/avatar_karan.png",
    fileType: "PDF",
    fileSize: "2.0 MB",
    pages: 35,
    uploadDate: "15 April 2024",
    rating: 4.7,
    ratingsCount: 110,
    downloads: 2000,
    tags: ["PYQs", "Past Exams", "Solves"],
    summary: "Comprehensive collection of university final exam questions for Computer Networks from the last 5 years, with detailed model answers and grading rubrics.",
    ownerId: "community",
    saved: false,
  },
  {
    id: "note-math-laplace",
    title: "Mathematics – Laplace Transforms",
    subject: "Mathematics",
    semester: "3",
    courseCode: "MA201",
    unit: "Unit 5",
    topic: "Transforms & Integrals",
    uploader: "Ishita Roy",
    uploaderRole: "CSE, 3rd Semester",
    uploaderAvatar: "/avatar_ishita.png",
    fileType: "PDF",
    fileSize: "1.1 MB",
    pages: 10,
    uploadDate: "10 April 2024",
    rating: 4.6,
    ratingsCount: 52,
    downloads: 1100,
    tags: ["Laplace", "Math", "Calculus", "Transforms"],
    summary: "Formulas and properties of Laplace and Inverse Laplace Transforms, step functions, Dirac delta, and differential equation solutions using Laplace transforms.",
    ownerId: "community",
    saved: false,
  },
  {
    id: "note-dld-kmaps",
    title: "Digital Logic – K Maps",
    subject: "Digital Logic Design",
    semester: "3",
    courseCode: "EC203",
    unit: "Unit 3",
    topic: "Minimization & combinational logic",
    uploader: "Devansh Jain",
    uploaderRole: "ECE, 3rd Semester",
    uploaderAvatar: "/avatar_devansh.png",
    fileType: "PDF",
    fileSize: "980 KB",
    pages: 8,
    uploadDate: "08 April 2024",
    rating: 4.8,
    ratingsCount: 64,
    downloads: 980,
    tags: ["K-Maps", "Logic Gates", "Minimization"],
    summary: "Clear tutorial on 2-variable, 3-variable, and 4-variable Karnaugh Maps, grouping cells, don't care conditions, and SOP/POS form logic design.",
    ownerId: "community",
    saved: false,
  },
  {
    id: "note-os-mem",
    title: "OS – Memory Management",
    subject: "Operating Systems",
    semester: "5",
    courseCode: "CS401",
    unit: "Unit 4",
    topic: "Paging, Virtual Memory & Swapping",
    uploader: "Neha Sharma",
    uploaderRole: "CSE, 5th Semester",
    uploaderAvatar: "/avatar_neha.png",
    fileType: "PDF",
    fileSize: "1.3 MB",
    pages: 14,
    uploadDate: "05 April 2024",
    rating: 4.7,
    ratingsCount: 78,
    downloads: 1300,
    tags: ["Paging", "Segmentation", "Virtual Memory"],
    summary: "Visual guide to memory paging, segmentation, page table structures, translation lookaside buffers (TLB), and page replacement algorithms (FIFO, LRU, Optimal).",
    ownerId: "community",
    saved: false,
  },
  {
    id: "note-cn-layered",
    title: "CN – Layered Architecture",
    subject: "Computer Networks",
    semester: "7",
    courseCode: "CS401",
    unit: "Unit 1",
    topic: "OSI Model & TCP/IP stack",
    uploader: "Aman Kumar",
    uploaderRole: "CSE, 7th Semester",
    uploaderAvatar: "/avatar_aman.png",
    fileType: "PDF",
    fileSize: "867 KB",
    pages: 6,
    uploadDate: "01 April 2024",
    rating: 4.5,
    ratingsCount: 45,
    downloads: 867,
    tags: ["OSI Model", "TCP/IP Stack", "Network Layers"],
    summary: "Introductory notes covering OSI 7-layer model vs TCP/IP 4-layer stack, functions of each layer, encapsulation/decapsulation, and basic networking devices.",
    ownerId: "community",
    saved: false,
  },
];
