#!/usr/bin/env bash
#
# Brings up the local Supabase stack, applies every migration, runs the pgTAP
# suites against it, and writes a .env.local pointing at it.
#
# This is the development database. It is disposable: `npm run db:reset` throws
# it away and rebuilds it from supabase/migrations, which is the whole point —
# nothing here can reach the project that serves real students.
#
# What it cannot do: hosted Auth settings. OAuth callbacks, Resend SMTP, and
# Turnstile enforcement live in a Supabase dashboard, not in config.toml. Local
# signup mail goes to Mailpit instead (printed at the end), and CAPTCHA is off,
# so the sign-up form accepts Cloudflare's always-passes test key. A real
# multi-user walkthrough still needs the hosted staging project in
# docs/staging.md.
#
# Usage:
#   scripts/bootstrap-local.sh
#
set -euo pipefail

cd "$(dirname "$0")/.."

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

step "1/5  Checking the container runtime"

# Docker Desktop only symlinks into /usr/local/bin when its privileged helper is
# installed. Declining that leaves a working daemon whose CLI lives under the
# home directory and whose socket is not /var/run/docker.sock, which is where
# both this script and the Supabase CLI would otherwise look.
if ! command -v docker >/dev/null 2>&1 && [ -x "$HOME/.docker/bin/docker" ]; then
  export PATH="$HOME/.docker/bin:$PATH"
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is not installed. Install Docker Desktop, then re-run this script." >&2
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  echo "Docker is installed but not running. Start Docker Desktop, then re-run this script." >&2
  exit 1
fi

# The Supabase CLI reads DOCKER_HOST but does not resolve Docker contexts, so a
# context-based install needs the endpoint handed to it explicitly.
if [ -z "${DOCKER_HOST:-}" ]; then
  context_host="$(docker context inspect --format '{{.Endpoints.docker.Host}}' 2>/dev/null || true)"
  if [ -n "$context_host" ] && [ "$context_host" != "unix:///var/run/docker.sock" ]; then
    export DOCKER_HOST="$context_host"
    echo "Using DOCKER_HOST=$DOCKER_HOST"
  fi
fi

step "2/5  Starting the local Supabase stack"
npx --no-install supabase start

step "3/5  Applying every migration to the local database"
npx --no-install supabase db reset

step "4/5  Running the pgTAP suites"
npx --no-install supabase test db

step "5/5  Writing .env.local"
if [ -f .env.local ]; then
  cp .env.local ".env.local.backup-$(date +%Y%m%d%H%M%S)"
  echo "Existing .env.local backed up."
fi

# `supabase status -o env` emits shell assignments. Newer CLIs publish the new
# PUBLISHABLE_KEY/SECRET_KEY pair alongside the legacy ANON_KEY/SERVICE_ROLE_KEY;
# take whichever this one gives us.
eval "$(npx --no-install supabase status -o env)"

API="${API_URL:-http://127.0.0.1:54321}"
PUBLISHABLE="${PUBLISHABLE_KEY:-${ANON_KEY:-}}"
SECRET="${SECRET_KEY:-${SERVICE_ROLE_KEY:-}}"

if [ -z "$PUBLISHABLE" ] || [ -z "$SECRET" ]; then
  echo "Could not read the local keys from \`supabase status\`." >&2
  exit 1
fi

cat > .env.local <<ENV
# Generated by scripts/bootstrap-local.sh — local Supabase stack only.
# Regenerate with that script; do not paste hosted credentials in here.
NEXT_PUBLIC_SUPABASE_URL=$API
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$PUBLISHABLE
SUPABASE_SERVICE_ROLE_KEY=$SECRET
CRON_SECRET=local-development-cron-secret
NEXT_PUBLIC_SITE_URL=http://localhost:3000
# Cloudflare's documented always-passes test key. Local GoTrue has CAPTCHA
# disabled (supabase/config.toml), so no secret key is needed to match it.
NEXT_PUBLIC_TURNSTILE_SITE_KEY=1x00000000000000000000AA
ENV

node scripts/check-env.mjs

cat <<'DONE'

Local stack is ready.

  npm run dev              http://localhost:3000
  Mailpit (signup mail)    http://127.0.0.1:54324
  Studio                   http://127.0.0.1:54323

  npm run db:test          re-run the pgTAP suites
  npm run db:reset         throw the database away and rebuild it
  npm run supabase:stop    stop the stack

Google/GitHub OAuth, real SMTP, and CAPTCHA enforcement are hosted settings and
are not available locally. Use email/password signup and read the confirmation
link out of Mailpit.
DONE
